import sys
import os
from message_mod import message
from signal_mod import signal
from board_mod import boards

def generate(board_list):

	if os.path.exists("output/memstruct.h"):
		try:
			os.remove("output/memstruct.h")
		except:
			print("ERROR: Failed to delete memstruct.h in output")
			sys.exit()
	
	with open("output/memstruct.h", "w+") as fo:
	
		# Start with headers guards, includes and defines
		str = (
			f"/* This file was generated by EclipseMemstructGen.py*/\n"
			f"\n"
			f"#ifndef MEMSTRUCT_H_\n"
			f"#define MEMSTRUCT_H_\n"
			f"\n"
			f"#ifndef E92_EXCLUDE_MAIN_MEMSTRUCT\n"
			f"\n"
			f"#include <stddef.h>\n"
			f"\n"
			f"#include \"can_cfg.h\"\n"
			f"#include \"can_sig.h\"\n"
			f"#include \"can_msg.h\"\n"
			f"#include \"can_frm.h\"\n"
			f"\n"
			f"#ifdef E92_USE_CUSTOM_MEMSTRUCT\n"
			f"       #include \"custom_memstruct.h\"\n"
			f"#endif\n"
			f"#include \"service_can_callbacks.h\"\n"
			f"\n"
			f"#define CANFRM_EXTENDED_ID  (1<<29)\n"
			f"#define CANFRM_RTR          (1<<30)\n"
			f"\n"
		)

		# Generate Callbacks
		board_callbacks_str = ""
		for board in board_list:
			board_callbacks_str += board.print_header()
			board_callbacks_str += board.print_callback()
		str += (
			f"/*Callback definition*/\n"
			f"{board_callbacks_str}"
		)

		# Generate Board enum
		board_enum_str = ""
		for board in board_list:
			board_enum_str += board.print_enum()
		str += (
			f"/*Board enum*/\n"
			f"enum{{\n"
			f"{board_enum_str}"
			f"}};\n"
		)

		# Generate Signal List
		signal_enum_str = ""
		for board in board_list:
			signal_enum_str += board.print_header()
			signal_enum_str += board.print_signal_enum()
		str += (
			f"/*Signal enum*/\n"
			f"enum{{\n"
			f"{signal_enum_str}"
			f"\n"
			f"#ifdef E92_USE_CUSTOM_MEMSTRUCT\n"
			f"        S_CUSTOM_SIGNALS_ID\n"
			f"#endif\n"
			f"}};\n"
		)

		# Generate Message List
		message_enum_str = ""
		for board in board_list:
			message_enum_str += board.print_header()
			message_enum_str += board.print_message_enum()
		str += (
			f"/*Message enum*/\n"
			f"enum{{\n"
			f"{message_enum_str}"
			f"}};\n"
			f"\n"
		)
		
		# Define M_max
		cnt = 0
		for board in board_list:
			cnt += board.message_cnt
		str += (
			f"#define M_MAX                 {cnt}\n"
			f"\n"
			f"#endif /*E92_EXCLUDE_MAIN_MEMSTRUCT*/\n"
			f"#endif\n"
		)
		
		# Writing to file
		fo.write(str)



